### ISSUE TITLE
Event Submission API

### ISSUE THREAD

**Issue by jnunemaker** [dailytics/plausible_api#7]
This is sweet. I didn't see any stuff for submitting events via the event API. Did I miss it? If not, would you be open to a pull request that adds it? They actually support doing it from ruby and it generally Just Works™ if you use the same user agent and remote ip. 

Sorry for opening an issue but I didn't see discussions turned on. Feel free to close this either way.

**Comment by luctus** [comment]
hey! Thanks a lot for giving this gem a try.

The initial objective was to consume their reporting API, but I'd be more than open to expand the goal. Please feel welcome to add new functionality :)

Cheers!
